from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from dataclasses import replace
from hashlib import sha256
from pathlib import Path
from typing import Any

from .generation import GenerationError, PublishedAsset


class GitHubReleasePublisher:
    def __init__(self, repository: str) -> None:
        self.repository = repository

    def publish(self, book_id: str, path: Path, asset_name: str) -> PublishedAsset:
        tag = self._tag(book_id)
        self._ensure_release(tag)
        existing = self._find_asset(tag, asset_name)
        local_hash = self._hash_file(path)
        if existing is not None:
            verified = self._verify_asset(existing, local_hash)
            if verified.byte_size != path.stat().st_size:
                raise GenerationError("REMOTE_ASSET_MISMATCH", "远端同名音频与本机内容不一致。")
            return replace(verified, created=False)

        upload_dir = Path(tempfile.mkdtemp(prefix="audiobook-upload-"))
        upload_path = upload_dir / asset_name
        try:
            shutil.copy2(path, upload_path)
            result = self._run([
                "gh",
                "release",
                "upload",
                tag,
                str(upload_path),
                "--repo",
                self.repository,
            ])
        finally:
            shutil.rmtree(upload_dir, ignore_errors=True)
        if result.returncode != 0:
            raise self._command_error(
                result,
                "GITHUB_UPLOAD_FAILED",
                "GitHub 音频上传中断，稍后会自动重试。",
            )
        remote = self._find_asset(tag, asset_name)
        if remote is None:
            raise GenerationError("GITHUB_VERIFY_FAILED", "上传后没有找到远端音频。")
        verified = self._verify_asset(remote, local_hash)
        if verified.byte_size != path.stat().st_size:
            raise GenerationError("REMOTE_ASSET_MISMATCH", "远端音频大小校验失败。")
        return verified

    def delete(self, book_id: str, asset_id: int) -> None:
        del book_id
        self.delete_verified(asset_id)

    def delete_verified(self, asset_id: int) -> None:
        result = self._run([
            "gh",
            "api",
            "--method",
            "DELETE",
            f"repos/{self.repository}/releases/assets/{asset_id}",
        ])
        if result.returncode != 0 and "HTTP 404" not in result.stderr:
            raise self._command_error(
                result,
                "GITHUB_DELETE_FAILED",
                "GitHub 音频暂时无法删除，稍后会自动重试。",
            )
        check = self._run([
            "gh",
            "api",
            f"repos/{self.repository}/releases/assets/{asset_id}",
        ])
        if check.returncode == 0:
            raise GenerationError("GITHUB_DELETE_VERIFY_FAILED", "远程音频仍然存在，稍后会再次核对。")
        if "HTTP 404" not in check.stderr:
            raise self._command_error(
                check,
                "GITHUB_DELETE_VERIFY_FAILED",
                "暂时无法确认远程音频已删除，稍后会再次核对。",
            )

    def list_assets(self, book_id: str) -> list[dict[str, Any]]:
        result = self._run([
            "gh",
            "release",
            "view",
            self._tag(book_id),
            "--repo",
            self.repository,
            "--json",
            "assets",
        ])
        if result.returncode != 0:
            if "release not found" in result.stderr.lower() or "HTTP 404" in result.stderr:
                return []
            raise self._command_error(
                result,
                "GITHUB_RESPONSE_INVALID",
                "暂时无法读取远程音频清单。",
            )
        try:
            value = json.loads(result.stdout)
        except json.JSONDecodeError as error:
            raise GenerationError("GITHUB_RESPONSE_INVALID", "GitHub 返回了无法识别的音频清单。") from error
        assets = value.get("assets", []) if isinstance(value, dict) else []
        return [item for item in assets if isinstance(item, dict)]

    def _ensure_release(self, tag: str) -> None:
        view = self._run(["gh", "release", "view", tag, "--repo", self.repository])
        if view.returncode == 0:
            return
        if self._is_limited(view.stderr):
            raise self._command_error(
                view,
                "GITHUB_RELEASE_FAILED",
                "无法读取公开音频发布区。",
            )
        created = self._run([
            "gh",
            "release",
            "create",
            tag,
            "--repo",
            self.repository,
            "--title",
            f"Audiobook assets: {tag}",
            "--notes",
            "Rights-confirmed audiobook assets generated by the user's Mac.",
        ])
        if created.returncode != 0:
            raise self._command_error(
                created,
                "GITHUB_RELEASE_FAILED",
                "无法创建公开音频发布区。",
            )

    def _find_asset(self, tag: str, asset_name: str) -> dict[str, Any] | None:
        result = self._run([
            "gh",
            "release",
            "view",
            tag,
            "--repo",
            self.repository,
            "--json",
            "assets",
        ])
        if result.returncode != 0:
            if self._is_limited(result.stderr):
                raise self._command_error(
                    result,
                    "GITHUB_RESPONSE_INVALID",
                    "暂时无法读取 GitHub 音频资产。",
                )
            return None
        try:
            assets = json.loads(result.stdout).get("assets", [])
        except json.JSONDecodeError as error:
            raise GenerationError("GITHUB_RESPONSE_INVALID", "GitHub 返回了无法识别的资产信息。") from error
        return next((item for item in assets if item.get("name") == asset_name), None)

    def _verify_asset(self, asset: dict[str, Any], expected_hash: str) -> PublishedAsset:
        try:
            asset_id = int(str(asset["apiUrl"]).rstrip("/").rsplit("/", 1)[-1])
        except (KeyError, ValueError) as error:
            raise GenerationError("GITHUB_ASSET_ID_INVALID", "GitHub 没有返回可验证的资产 ID。") from error
        fd, name = tempfile.mkstemp(prefix="audiobook-verify-")
        os.close(fd)
        target = Path(name)
        try:
            result = self._download(asset_id, target)
            if result.returncode != 0 or self._hash_file(target) != expected_hash:
                if result.returncode != 0 and self._is_limited(result.stderr):
                    raise self._command_error(
                        result,
                        "REMOTE_HASH_MISMATCH",
                        "远端音频下载校验失败。",
                    )
                raise GenerationError("REMOTE_HASH_MISMATCH", "远端音频 SHA-256 校验失败。")
            return PublishedAsset(
                asset_id=asset_id,
                name=str(asset["name"]),
                url=str(asset.get("url") or asset.get("browser_download_url") or ""),
                byte_size=target.stat().st_size,
                sha256=expected_hash,
            )
        finally:
            target.unlink(missing_ok=True)

    def _download(self, asset_id: int, target: Path) -> subprocess.CompletedProcess[bytes]:
        with target.open("wb") as output:
            return subprocess.run(
                [
                    "gh",
                    "api",
                    f"repos/{self.repository}/releases/assets/{asset_id}",
                    "-H",
                    "Accept: application/octet-stream",
                ],
                stdout=output,
                stderr=subprocess.PIPE,
                check=False,
            )

    @staticmethod
    def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
        return subprocess.run(command, capture_output=True, text=True, check=False)

    @staticmethod
    def _is_limited(stderr: str | bytes) -> bool:
        text = stderr.decode(errors="replace") if isinstance(stderr, bytes) else stderr
        lowered = text.lower()
        return any(marker in lowered for marker in (
            "http 429",
            "rate limit",
            "secondary rate limit",
            "api rate limit exceeded",
            "http 403: you have exceeded",
        ))

    @classmethod
    def _command_error(
        cls,
        result: subprocess.CompletedProcess[Any],
        code: str,
        message: str,
    ) -> GenerationError:
        if cls._is_limited(result.stderr):
            return GenerationError(
                "GITHUB_LIMITED",
                "GitHub 暂时限制请求，已自动退避，不会改用付费服务。",
            )
        return GenerationError(code, message)

    @staticmethod
    def _tag(book_id: str) -> str:
        return f"book-{book_id}"

    @staticmethod
    def _hash_file(path: Path) -> str:
        digest = sha256()
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
        return digest.hexdigest()
