from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from dataclasses import replace
from hashlib import sha256
from pathlib import Path
from typing import Any

from .generation import GenerationError, PublishedAsset


class GitHubReleasePublisher:
    def __init__(self, repository: str) -> None:
        self.repository = repository

    def publish(self, book_id: str, path: Path, asset_name: str) -> PublishedAsset:
        tag = self._tag(book_id)
        self._ensure_release(tag)
        existing = self._find_asset(tag, asset_name)
        local_hash = self._hash_file(path)
        if existing is not None:
            verified = self._verify_asset(existing, local_hash)
            if verified.byte_size != path.stat().st_size:
                raise GenerationError("REMOTE_ASSET_MISMATCH", "远端同名音频与本机内容不一致。")
            return replace(verified, created=False)

        upload_dir = Path(tempfile.mkdtemp(prefix="audiobook-upload-"))
        upload_path = upload_dir / asset_name
        try:
            shutil.copy2(path, upload_path)
            result = self._run([
                "gh",
                "release",
                "upload",
                tag,
                str(upload_path),
                "--repo",
                self.repository,
            ])
        finally:
            shutil.rmtree(upload_dir, ignore_errors=True)
        if result.returncode != 0:
            raise GenerationError("GITHUB_UPLOAD_FAILED", "GitHub 音频上传中断，稍后会自动重试。")
        remote = self._find_asset(tag, asset_name)
        if remote is None:
            raise GenerationError("GITHUB_VERIFY_FAILED", "上传后没有找到远端音频。")
        verified = self._verify_asset(remote, local_hash)
        if verified.byte_size != path.stat().st_size:
            raise GenerationError("REMOTE_ASSET_MISMATCH", "远端音频大小校验失败。")
        return verified

    def delete(self, book_id: str, asset_id: int) -> None:
        result = self._run([
            "gh",
            "api",
            "--method",
            "DELETE",
            f"repos/{self.repository}/releases/assets/{asset_id}",
        ])
        if result.returncode != 0 and "HTTP 404" not in result.stderr:
            raise GenerationError("GITHUB_ROLLBACK_FAILED", "迟到资产未能自动回滚，需要稍后对账。")

    def _ensure_release(self, tag: str) -> None:
        view = self._run(["gh", "release", "view", tag, "--repo", self.repository])
        if view.returncode == 0:
            return
        created = self._run([
            "gh",
            "release",
            "create",
            tag,
            "--repo",
            self.repository,
            "--title",
            f"Audiobook assets: {tag}",
            "--notes",
            "Rights-confirmed audiobook assets generated by the user's Mac.",
        ])
        if created.returncode != 0:
            raise GenerationError("GITHUB_RELEASE_FAILED", "无法创建公开音频发布区。")

    def _find_asset(self, tag: str, asset_name: str) -> dict[str, Any] | None:
        result = self._run([
            "gh",
            "release",
            "view",
            tag,
            "--repo",
            self.repository,
            "--json",
            "assets",
        ])
        if result.returncode != 0:
            return None
        try:
            assets = json.loads(result.stdout).get("assets", [])
        except json.JSONDecodeError as error:
            raise GenerationError("GITHUB_RESPONSE_INVALID", "GitHub 返回了无法识别的资产信息。") from error
        return next((item for item in assets if item.get("name") == asset_name), None)

    def _verify_asset(self, asset: dict[str, Any], expected_hash: str) -> PublishedAsset:
        try:
            asset_id = int(str(asset["apiUrl"]).rstrip("/").rsplit("/", 1)[-1])
        except (KeyError, ValueError) as error:
            raise GenerationError("GITHUB_ASSET_ID_INVALID", "GitHub 没有返回可验证的资产 ID。") from error
        fd, name = tempfile.mkstemp(prefix="audiobook-verify-")
        os.close(fd)
        target = Path(name)
        try:
            result = self._download(asset_id, target)
            if result.returncode != 0 or self._hash_file(target) != expected_hash:
                raise GenerationError("REMOTE_HASH_MISMATCH", "远端音频 SHA-256 校验失败。")
            return PublishedAsset(
                asset_id=asset_id,
                name=str(asset["name"]),
                url=str(asset.get("url") or asset.get("browser_download_url") or ""),
                byte_size=target.stat().st_size,
                sha256=expected_hash,
            )
        finally:
            target.unlink(missing_ok=True)

    def _download(self, asset_id: int, target: Path) -> subprocess.CompletedProcess[bytes]:
        with target.open("wb") as output:
            return subprocess.run(
                [
                    "gh",
                    "api",
                    f"repos/{self.repository}/releases/assets/{asset_id}",
                    "-H",
                    "Accept: application/octet-stream",
                ],
                stdout=output,
                stderr=subprocess.PIPE,
                check=False,
            )

    @staticmethod
    def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
        return subprocess.run(command, capture_output=True, text=True, check=False)

    @staticmethod
    def _tag(book_id: str) -> str:
        return f"book-{book_id}"

    @staticmethod
    def _hash_file(path: Path) -> str:
        digest = sha256()
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
        return digest.hexdigest()
